name: metalink
description: URL metadata extraction package for Dart, providing rich link previews with image manipulation capabilities.
version: 1.0.0
repository: https://github.com/omar-hanafy/metalink

topics:
  - metadata
  - url
  - preview
  - link
  - metadata-extraction

environment:
  sdk: ^3.0.0

dependencies:
  http: ^1.3.0
  html: ^0.15.5
  path: ^1.9.1
  hive_ce: ^2.10.1
  dart_helper_utils: ^4.1.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
  mockito: ^5.4.5
  build_runner: ^2.4.15
  very_good_analysis: 7.0.0
